% DNSim export from LEMS
% 
% Please note that this is a work in progress and only works for a limited subset of LEMS/NeuroML 2!!
%     This DNSim file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
%          org.neuroml.export  v1.4.1
%          org.neuroml.model   v1.4.1
%          jLEMS               v0.9.7.3
% Components:
%     fn1 (Type: fitzHughNagumoCell:  I=0.8 (dimensionless) SEC=1.0 (SI time))
%     net1 (Type: network)
%     sim1 (Type: Simulation:  length=200.0 (SI time) step=0.05 (SI time))
% 

spec=[];
spec.nodes(1).label = 'fn1_flat';
spec.nodes(1).multiplicity = 1;
spec.nodes(1).dynamics = {};
spec.nodes(1).mechanisms = {'fn1_flat_dnsim'};

% open model: fn1_flat in DNSim GUI
dnsim(spec); 


